// Country to power data mapping (voltage and frequency)
export const countryPowerData = {
  "Türkiye": { voltage: "400 V", frequency: "50 Hz" },
  "Almanya": { voltage: "400 V", frequency: "50 Hz" },
  "Fransa": { voltage: "400 V", frequency: "50 Hz" },
  "İtalya": { voltage: "400 V", frequency: "50 Hz" },
  "Birleşik Krallık": { voltage: "400 V", frequency: "50 Hz" },
  "Amerika Birleşik Devletleri": { voltage: "208/480/600 V", frequency: "60 Hz" },
  "Kanada": { voltage: "208/480/600 V", frequency: "60 Hz" },
  "Japonya": { voltage: "200 V", frequency: "50/60 Hz" },
  "Çin": { voltage: "380 V", frequency: "50 Hz" },
  "Hindistan": { voltage: "415 V", frequency: "50 Hz" },
  "Avustralya": { voltage: "400 V", frequency: "50 Hz" },
  "Brezilya": { voltage: "220/380 V", frequency: "60 Hz" },
  "Rusya": { voltage: "380 V", frequency: "50 Hz" },
  "Güney Kore": { voltage: "380 V", frequency: "60 Hz" },
  "Meksika": { voltage: "220/440 V", frequency: "60 Hz" },
  "Suudi Arabistan": { voltage: "380/220 V", frequency: "60 Hz" },
  "Arjantin": { voltage: "380 V", frequency: "50 Hz" },
  "Bangladeş": { voltage: "400 V", frequency: "50 Hz" },
  "Endonezya": { voltage: "400 V", frequency: "50 Hz" },
  "Mısır": { voltage: "380 V", frequency: "50 Hz" },
  "Pakistan": { voltage: "400 V", frequency: "50 Hz" },
  "Vietnam": { voltage: "380 V", frequency: "50 Hz" },
  "Nijerya": { voltage: "415 V", frequency: "50 Hz" },
  "Güney Afrika": { voltage: "400 V", frequency: "50 Hz" },
  "Kenya": { voltage: "415 V", frequency: "50 Hz" },
  "Malezya": { voltage: "400 V", frequency: "50 Hz" },
  "Tayland": { voltage: "400 V", frequency: "50 Hz" },
  "Filipinler": { voltage: "380 V", frequency: "60 Hz" },
  "Kolombiya": { voltage: "220/440 V", frequency: "60 Hz" },
  "Şili": { voltage: "380 V", frequency: "50 Hz" },
  "Peru": { voltage: "220 V", frequency: "60 Hz" },
  "Venezuela": { voltage: "120 V", frequency: "60 Hz" },
  "Norveç": { voltage: "230/400 V", frequency: "50 Hz" },
  "İsveç": { voltage: "400 V", frequency: "50 Hz" },
  "Finlandiya": { voltage: "400 V", frequency: "50 Hz" },
  "Polonya": { voltage: "400 V", frequency: "50 Hz" },
  "Çek Cumhuriyeti": { voltage: "400 V", frequency: "50 Hz" },
  "Macaristan": { voltage: "400 V", frequency: "50 Hz" },
  "Romanya": { voltage: "400 V", frequency: "50 Hz" },
  "Bulgaristan": { voltage: "400 V", frequency: "50 Hz" },
  "Yunanistan": { voltage: "400 V", frequency: "50 Hz" },
  "Hollanda": { voltage: "400 V", frequency: "50 Hz" },
  "Belçika": { voltage: "400 V", frequency: "50 Hz" },
  "İspanya": { voltage: "400 V", frequency: "50 Hz" },
  "Portekiz": { voltage: "400 V", frequency: "50 Hz" },
  "İsviçre": { voltage: "400 V", frequency: "50 Hz" },
  "Avusturya": { voltage: "400 V", frequency: "50 Hz" },
  "Danimarka": { voltage: "400 V", frequency: "50 Hz" },
  "İrlanda": { voltage: "400 V", frequency: "50 Hz" },
  "İzlanda": { voltage: "400 V", frequency: "50 Hz" },
  "Lüksemburg": { voltage: "400 V", frequency: "50 Hz" },
  "Slovenya": { voltage: "400 V", frequency: "50 Hz" },
  "Slovakya": { voltage: "400 V", frequency: "50 Hz" },
  "Hırvatistan": { voltage: "400 V", frequency: "50 Hz" },
  "Sırbistan": { voltage: "400 V", frequency: "50 Hz" },
  "Bosna Hersek": { voltage: "400 V", frequency: "50 Hz" },
  "Karadağ": { voltage: "400 V", frequency: "50 Hz" },
  "Kuzey Makedonya": { voltage: "400 V", frequency: "50 Hz" },
  "Arnavutluk": { voltage: "400 V", frequency: "50 Hz" },
  "Estonya": { voltage: "400 V", frequency: "50 Hz" },
  "Letonya": { voltage: "400 V", frequency: "50 Hz" },
  "Litvanya": { voltage: "400 V", frequency: "50 Hz" },
  "Beyaz Rusya": { voltage: "380 V", frequency: "50 Hz" },
  "Ukrayna": { voltage: "400 V", frequency: "50 Hz" },
  "Moldova": { voltage: "400 V", frequency: "50 Hz" },
  "Gürcistan": { voltage: "380 V", frequency: "50 Hz" },
  "Ermenistan": { voltage: "400 V", frequency: "50 Hz" },
  "Azerbaycan": { voltage: "380 V", frequency: "50 Hz" },
  "Kazakistan": { voltage: "380 V", frequency: "50 Hz" },
  "Özbekistan": { voltage: "380 V", frequency: "50 Hz" },
  "Türkmenistan": { voltage: "380 V", frequency: "50 Hz" },
  "Kırgızistan": { voltage: "380 V", frequency: "50 Hz" },
  "Tacikistan": { voltage: "380 V", frequency: "50 Hz" },
  "Afganistan": { voltage: "380 V", frequency: "50 Hz" },
  "İran": { voltage: "400 V", frequency: "50 Hz" },
  "Irak": { voltage: "400 V", frequency: "50 Hz" },
  "Suriye": { voltage: "400 V", frequency: "50 Hz" },
  "Lübnan": { voltage: "400 V", frequency: "50 Hz" },
  "Ürdün": { voltage: "400 V", frequency: "50 Hz" },
  "İsrail": { voltage: "400 V", frequency: "50 Hz" },
  "Kuveyt": { voltage: "400 V", frequency: "50 Hz" },
  "Bahreyn": { voltage: "400 V", frequency: "50 Hz" },
  "Katar": { voltage: "400 V", frequency: "50 Hz" },
  "Birleşik Arap Emirlikleri": { voltage: "400 V", frequency: "50 Hz" },
  "Umman": { voltage: "400 V", frequency: "50 Hz" },
  "Yemen": { voltage: "400 V", frequency: "50 Hz" },
  "Sudan": { voltage: "400 V", frequency: "50 Hz" },
  "Etiyopya": { voltage: "380 V", frequency: "50 Hz" },
  "Somali": { voltage: "400 V", frequency: "50 Hz" },
  "Tanzanya": { voltage: "400 V", frequency: "50 Hz" },
  "Uganda": { voltage: "415 V", frequency: "50 Hz" },
  "Zambiya": { voltage: "400 V", frequency: "50 Hz" },
  "Zimbabve": { voltage: "400 V", frequency: "50 Hz" },
  "Angola": { voltage: "380 V", frequency: "50 Hz" },
  "Mozambik": { voltage: "380 V", frequency: "50 Hz" },
  "Namibya": { voltage: "380 V", frequency: "50 Hz" },
  "Botsvana": { voltage: "400 V", frequency: "50 Hz" },
  "Lesotho": { voltage: "380 V", frequency: "50 Hz" },
  "Esvatini": { voltage: "400 V", frequency: "50 Hz" },
  "Madagaskar": { voltage: "380 V", frequency: "50 Hz" },
  "Mauritius": { voltage: "400 V", frequency: "50 Hz" },
  "Seyşeller": { voltage: "400 V", frequency: "50 Hz" },
  "Malavi": { voltage: "400 V", frequency: "50 Hz" },
  "Ruanda": { voltage: "400 V", frequency: "50 Hz" },
  "Burundi": { voltage: "380 V", frequency: "50 Hz" },
  "Kongo": { voltage: "400 V", frequency: "50 Hz" },
  "Kongo Demokratik Cumhuriyeti": { voltage: "400 V", frequency: "50 Hz" },
  "Kamerun": { voltage: "380 V", frequency: "50 Hz" },
  "Nijer": { voltage: "380 V", frequency: "50 Hz" },
  "Çad": { voltage: "380 V", frequency: "50 Hz" },
  "Mali": { voltage: "380 V", frequency: "50 Hz" },
  "Burkina Faso": { voltage: "380 V", frequency: "50 Hz" },
  "Senegal": { voltage: "400 V", frequency: "50 Hz" },
  "Gine": { voltage: "380 V", frequency: "50 Hz" },
  "Gine-Bissau": { voltage: "380 V", frequency: "50 Hz" },
  "Sierra Leone": { voltage: "400 V", frequency: "50 Hz" },
  "Liberya": { voltage: "208 V", frequency: "60 Hz" },
  "Fildişi Sahili": { voltage: "380 V", frequency: "50 Hz" },
  "Gana": { voltage: "400 V", frequency: "50 Hz" },
  "Togo": { voltage: "380 V", frequency: "50 Hz" },
  "Benin": { voltage: "380 V", frequency: "50 Hz" },
  "Gabon": { voltage: "380 V", frequency: "50 Hz" },
  "Ekvator Ginesi": { voltage: "400 V", frequency: "50 Hz" },
  "Orta Afrika Cumhuriyeti": { voltage: "380 V", frequency: "50 Hz" },
  "Güney Sudan": { voltage: "400 V", frequency: "50 Hz" },
  "Eritre": { voltage: "400 V", frequency: "50 Hz" },
  "Cibuti": { voltage: "380 V", frequency: "50 Hz" },
  "Maldivler": { voltage: "400 V", frequency: "50 Hz" },
  "Sri Lanka": { voltage: "400 V", frequency: "50 Hz" },
  "Nepal": { voltage: "400 V", frequency: "50 Hz" },
  "Bhutan": { voltage: "400 V", frequency: "50 Hz" },
  "Myanmar": { voltage: "400 V", frequency: "50 Hz" },
  "Laos": { voltage: "400 V", frequency: "50 Hz" },
  "Yeni Zelanda": { voltage: "400 V", frequency: "50 Hz" },
  "Singapur": { voltage: "400 V", frequency: "50 Hz" },
  "Fas": { voltage: "380 V", frequency: "50 Hz" },
  "Tunus": { voltage: "380 V", frequency: "50 Hz" },
  "Cezayir": { voltage: "380 V", frequency: "50 Hz" },
  "Kıbrıs": { voltage: "400 V", frequency: "50 Hz" },
  "Malta": { voltage: "400 V", frequency: "50 Hz" },
  "Andorra": { voltage: "400 V", frequency: "50 Hz" },
  // Yeni eklenen ülkeler
  "Antigua ve Barbuda": { voltage: "230 V", frequency: "60 Hz" },
  "Bahamalar": { voltage: "120 V", frequency: "60 Hz" },
  "Barbados": { voltage: "115 V", frequency: "50 Hz" },
  "Belize": { voltage: "110/220 V", frequency: "60 Hz" },
  "Bolivya": { voltage: "220/400 V", frequency: "50 Hz" },
  "Brunei": { voltage: "240 V", frequency: "50 Hz" },
  "Dominik Cumhuriyeti": { voltage: "110 V", frequency: "60 Hz" },
  "Dominika": { voltage: "230 V", frequency: "50 Hz" },
  "Ekvador": { voltage: "120 V", frequency: "60 Hz" },
  "El Salvador": { voltage: "115 V", frequency: "60 Hz" },
  "Fiji": { voltage: "240 V", frequency: "50 Hz" },
  "Gambiya": { voltage: "230 V", frequency: "50 Hz" },
  "Grenada": { voltage: "230 V", frequency: "50 Hz" },
  "Guyana": { voltage: "240 V", frequency: "60 Hz" },
  "Guatemala": { voltage: "120 V", frequency: "60 Hz" },
  "Haiti": { voltage: "110 V", frequency: "60 Hz" },
  "Honduras": { voltage: "110 V", frequency: "60 Hz" },
  "Jamaika": { voltage: "110 V", frequency: "50 Hz" },
  "Kamboçya": { voltage: "230 V", frequency: "50 Hz" },
  "Kiribati": { voltage: "240 V", frequency: "50 Hz" },
  "Komorlar": { voltage: "220 V", frequency: "50 Hz" },
  "Kosova": { voltage: "230 V", frequency: "50 Hz" },
  "Kosta Rika": { voltage: "120 V", frequency: "60 Hz" },
  "Kuzey Kore": { voltage: "220 V", frequency: "60 Hz" },
  "Küba": { voltage: "110 V", frequency: "60 Hz" },
  "Liechtenstein": { voltage: "230 V", frequency: "50 Hz" },
  "Marshall Adaları": { voltage: "120 V", frequency: "60 Hz" },
  "Mikronezya": { voltage: "120 V", frequency: "60 Hz" },
  "Moğolistan": { voltage: "230 V", frequency: "50 Hz" },
  "Monako": { voltage: "230 V", frequency: "50 Hz" },
  "Moritanya": { voltage: "220 V", frequency: "50 Hz" },
  "Nauru": { voltage: "240 V", frequency: "50 Hz" },
  "Nikaragua": { voltage: "120 V", frequency: "60 Hz" },
  "Palau": { voltage: "120 V", frequency: "60 Hz" },
  "Panama": { voltage: "110 V", frequency: "60 Hz" },
  "Papua Yeni Gine": { voltage: "240 V", frequency: "50 Hz" },
  "Paraguay": { voltage: "220 V", frequency: "50 Hz" },
  "Saint Kitts ve Nevis": { voltage: "230 V", frequency: "60 Hz" },
  "Saint Lucia": { voltage: "240 V", frequency: "50 Hz" },
  "Saint Vincent ve Grenadinler": { voltage: "230 V", frequency: "50 Hz" },
  "Samoa": { voltage: "230 V", frequency: "50 Hz" },
  "San Marino": { voltage: "230 V", frequency: "50 Hz" },
  "Sao Tome ve Principe": { voltage: "220 V", frequency: "50 Hz" },
  "Solomon Adaları": { voltage: "230 V", frequency: "50 Hz" },
  "Surinam": { voltage: "127 V", frequency: "60 Hz" },
  "Tayvan": { voltage: "110 V", frequency: "60 Hz" },
  "Tonga": { voltage: "240 V", frequency: "50 Hz" },
  "Trinidad ve Tobago": { voltage: "115 V", frequency: "60 Hz" },
  "Tuvalu": { voltage: "220 V", frequency: "50 Hz" },
  "Uruguay": { voltage: "220 V", frequency: "50 Hz" },
  "Vanuatu": { voltage: "230 V", frequency: "50 Hz" },
  "Vatikan": { voltage: "230 V", frequency: "50 Hz" },
  "Yeşil Burun Adaları": { voltage: "220 V", frequency: "50 Hz" }
}

export default countryPowerData