// Comprehensive country mappings for Vue application
// This file contains mappings between Turkish and English country names
// to ensure the API can recognize country names when users select Turkish names

export const countryMappings = {
  // Turkish to English country name mappings
  "Afganistan": "Afghanistan",
  "Almanya": "Germany",
  "Amerika Birleşik Devletleri": "United States",
  "Andorra": "Andorra",
  "Angola": "Angola",
  "Antigua ve Barbuda": "Antigua and Barbuda",
  "Arjantin": "Argentina",
  "Arnavutluk": "Albania",
  "Avustralya": "Australia",
  "Avusturya": "Austria",
  "Azerbaycan": "Azerbaijan",
  "Bahamalar": "Bahamas",
  "Bahreyn": "Bahrain",
  "Bangladeş": "Bangladesh",
  "Barbados": "Barbados",
  "Belçika": "Belgium",
  "Belize": "Belize",
  "Benin": "Benin",
  "Beyaz Rusya": "Belarus",
  "Bhutan": "Bhutan",
  "Birleşik Arap Emirlikleri": "United Arab Emirates",
  "Birleşik Krallık": "United Kingdom",
  "Bolivya": "Bolivia",
  "Bosna Hersek": "Bosnia and Herzegovina",
  "Botsvana": "Botswana",
  "Brezilya": "Brazil",
  "Brunei": "Brunei",
  "Bulgaristan": "Bulgaria",
  "Burkina Faso": "Burkina Faso",
  "Burundi": "Burundi",
  "Cezayir": "Algeria",
  "Cibuti": "Djibouti",
  "Çad": "Chad",
  "Çek Cumhuriyeti": "Czech Republic",
  "Çin": "China",
  "Danimarka": "Denmark",
  "Doğu Timor": "East Timor",
  "Dominik Cumhuriyeti": "Dominican Republic",
  "Dominika": "Dominica",
  "Ekvador": "Ecuador",
  "Ekvator Ginesi": "Equatorial Guinea",
  "El Salvador": "El Salvador",
  "Endonezya": "Indonesia",
  "Eritre": "Eritrea",
  "Ermenistan": "Armenia",
  "Estonya": "Estonia",
  "Esvatini": "Eswatini",
  "Etiyopya": "Ethiopia",
  "Fas": "Morocco",
  "Fiji": "Fiji",
  "Fildişi Sahili": "Ivory Coast",
  "Filipinler": "Philippines",
  "Finlandiya": "Finland",
  "Fransa": "France",
  "Gabon": "Gabon",
  "Gambiya": "Gambia",
  "Gana": "Ghana",
  "Gine": "Guinea",
  "Gine-Bissau": "Guinea-Bissau",
  "Grenada": "Grenada",
  "Guyana": "Guyana",
  "Guatemala": "Guatemala",
  "Güney Afrika": "South Africa",
  "Güney Kore": "South Korea",
  "Güney Sudan": "South Sudan",
  "Gürcistan": "Georgia",
  "Haiti": "Haiti",
  "Hırvatistan": "Croatia",
  "Hindistan": "India",
  "Hollanda": "Netherlands",
  "Honduras": "Honduras",
  "Irak": "Iraq",
  "İran": "Iran",
  "İrlanda": "Ireland",
  "İspanya": "Spain",
  "İsrail": "Israel",
  "İsveç": "Sweden",
  "İsviçre": "Switzerland",
  "İtalya": "Italy",
  "İzlanda": "Iceland",
  "Jamaika": "Jamaica",
  "Japonya": "Japan",
  "Kamboçya": "Cambodia",
  "Kamerun": "Cameroon",
  "Kanada": "Canada",
  "Karadağ": "Montenegro",
  "Katar": "Qatar",
  "Kazakistan": "Kazakhstan",
  "Kenya": "Kenya",
  "Kıbrıs": "Cyprus",
  "Kırgızistan": "Kyrgyzstan",
  "Kiribati": "Kiribati",
  "Kolombiya": "Colombia",
  "Komorlar": "Comoros",
  "Kongo": "Congo",
  "Kongo Demokratik Cumhuriyeti": "Democratic Republic of the Congo",
  "Kosova": "Kosovo",
  "Kosta Rika": "Costa Rica",
  "Kuveyt": "Kuwait",
  "Kuzey Kore": "North Korea",
  "Kuzey Makedonya": "North Macedonia",
  "Küba": "Cuba",
  "Laos": "Laos",
  "Lesotho": "Lesotho",
  "Letonya": "Latvia",
  "Liberya": "Liberia",
  "Libya": "Libya",
  "Liechtenstein": "Liechtenstein",
  "Litvanya": "Lithuania",
  "Lübnan": "Lebanon",
  "Lüksemburg": "Luxembourg",
  "Macaristan": "Hungary",
  "Madagaskar": "Madagascar",
  "Malavi": "Malawi",
  "Maldivler": "Maldives",
  "Malezya": "Malaysia",
  "Mali": "Mali",
  "Malta": "Malta",
  "Marshall Adaları": "Marshall Islands",
  "Mauritius": "Mauritius",
  "Meksika": "Mexico",
  "Mısır": "Egypt",
  "Mikronezya": "Micronesia",
  "Moğolistan": "Mongolia",
  "Moldova": "Moldova",
  "Monako": "Monaco",
  "Moritanya": "Mauritania",
  "Mozambik": "Mozambique",
  "Myanmar": "Myanmar",
  "Namibya": "Namibia",
  "Nauru": "Nauru",
  "Nepal": "Nepal",
  "Nijer": "Niger",
  "Nijerya": "Nigeria",
  "Nikaragua": "Nicaragua",
  "Norveç": "Norway",
  "Orta Afrika Cumhuriyeti": "Central African Republic",
  "Özbekistan": "Uzbekistan",
  "Pakistan": "Pakistan",
  "Palau": "Palau",
  "Panama": "Panama",
  "Papua Yeni Gine": "Papua New Guinea",
  "Paraguay": "Paraguay",
  "Peru": "Peru",
  "Polonya": "Poland",
  "Portekiz": "Portugal",
  "Romanya": "Romania",
  "Ruanda": "Rwanda",
  "Rusya": "Russia",
  "Saint Kitts ve Nevis": "Saint Kitts and Nevis",
  "Saint Lucia": "Saint Lucia",
  "Saint Vincent ve Grenadinler": "Saint Vincent and the Grenadines",
  "Samoa": "Samoa",
  "San Marino": "San Marino",
  "Sao Tome ve Principe": "Sao Tome and Principe",
  "Senegal": "Senegal",
  "Seyşeller": "Seychelles",
  "Sırbistan": "Serbia",
  "Sierra Leone": "Sierra Leone",
  "Singapur": "Singapore",
  "Slovakya": "Slovakia",
  "Slovenya": "Slovenia",
  "Solomon Adaları": "Solomon Islands",
  "Somali": "Somalia",
  "Sri Lanka": "Sri Lanka",
  "Sudan": "Sudan",
  "Surinam": "Suriname",
  "Suriye": "Syria",
  "Suudi Arabistan": "Saudi Arabia",
  "Şili": "Chile",
  "Tacikistan": "Tajikistan",
  "Tanzanya": "Tanzania",
  "Tayland": "Thailand",
  "Tayvan": "Taiwan",
  "Togo": "Togo",
  "Tonga": "Tonga",
  "Trinidad ve Tobago": "Trinidad and Tobago",
  "Tunus": "Tunisia",
  "Tuvalu": "Tuvalu",
  "Türkiye": "Turkey",
  "Türkmenistan": "Turkmenistan",
  "Uganda": "Uganda",
  "Ukrayna": "Ukraine",
  "Umman": "Oman",
  "Uruguay": "Uruguay",
  "Ürdün": "Jordan",
  "Vanuatu": "Vanuatu",
  "Vatikan": "Vatican City",
  "Venezuela": "Venezuela",
  "Vietnam": "Vietnam",
  "Yemen": "Yemen",
  "Yeni Zelanda": "New Zealand",
  "Yeşil Burun Adaları": "Cape Verde",
  "Yunanistan": "Greece",
  "Zambiya": "Zambia",
  "Zimbabve": "Zimbabwe",
  // Additional Turkish variants
  "ABD": "United States of America",
  "AB": "European Union",
  "Amerika": "United States of America",
  "İngiltere": "United Kingdom",
  "Birleşik Devletler": "United States of America",
  "Çin Halk Cumhuriyeti": "China",
  "Rusya Federasyonu": "Russian Federation",
  "Suudi": "Saudi Arabia",
  "BAE": "United Arab Emirates",
  "Güney Kıbrıs": "Cyprus",
  "KKTC": "Northern Cyprus", 
  "Kuzey Kıbrıs": "Northern Cyprus",
  "Kıbrıs Cumhuriyeti": "Cyprus",
  "Filistin": "Palestine",
  "Kuzey Kıbrıs Türk Cumhuriyeti": "Northern Cyprus"
}

// Add English to English mappings for common variations
export const englishVariations = {
  "United States": "United States of America",
  "USA": "United States of America",
  "UK": "United Kingdom",
  "Great Britain": "United Kingdom",
  "UAE": "United Arab Emirates",
  "Russia": "Russian Federation",
  "South Korea": "Korea, South",
  "North Korea": "Korea, North"
}

// API specific country name mappings for alternative formats
// These are used when the first attempt to fetch states fails
export const apiSpecificMappings = {
  "United States": "United States of America",
  "United States of America": "USA",
  "USA": "United States",
  "Russia": "Russian Federation",
  "Russian Federation": "Russia",
  "UK": "United Kingdom",
  "United Kingdom": "UK",
  "South Korea": "Korea, South",
  "North Korea": "Korea, North",
  "Turkey": "Turkiye",
  "Turkiye": "Turkey",
  "China": "China, People's Republic of",
  "UAE": "United Arab Emirates",
  "Palestine": "Palestinian Territory",
  "Tanzania": "Tanzania, United Republic of",
  "Iran": "Iran, Islamic Republic of",
  "Venezuela": "Venezuela, Bolivarian Republic of",
  "Syria": "Syrian Arab Republic",
  "Vietnam": "Viet Nam",
  "Laos": "Lao People's Democratic Republic",
  "Moldova": "Moldova, Republic of",
  "Macedonia": "North Macedonia",
  "Republic of Ireland": "Ireland",
  "Congo": "Congo, Republic of the",
  "Democratic Republic of the Congo": "Congo, Democratic Republic of the"
}

// Merge both mappings
Object.assign(countryMappings, englishVariations)

// Helper function to try alternative country name formats
export const tryAlternativeCountryName = (countryName) => {
  return apiSpecificMappings[countryName] || countryName
}

// Helper function to get English country name from Turkish
export const getEnglishCountryName = (turkishName) => {
  return countryMappings[turkishName] || turkishName
}
